### ISSUE TITLE
Ultrasonic Android on Madsonic Server

### ISSUE THREAD

**Issue by sergiocos** [ErickSimoes/Ultrasonic#43]
Hi! I'm using an older version of Madsonic server, latest free, without activation (MADSONIC 5.1.5260.20150831.0820) and after your latest update your android client can't connect to server. (A network error ocurred. Please check the server address or try again.)
Thank you for all your work!

**Comment by ErickSimoes** [comment]
Hi @sergiocos!
Can you explain in more detail how this library is being used on Android?
It was designed for Arduino and, until then, I am not aware of its use on other platforms.

Thank you.

**Comment by sergiocos** [comment]
sorry, wrong app, i wanted to post here: https://github.com/ultrasonic/ultrasonic. I will not posting again before coffee

**Comment by ErickSimoes** [comment]
No problem.
Good coffee for you :+1:
