### ISSUE TITLE
No longer use the 'pulseIn()' method

### ISSUE THREAD

**Issue by ErickSimoes** [ErickSimoes/Ultrasonic#45]
Apparently, when this library is used on a non-Arduino-based device, the `pulseIn()` method, used to wait the echo, causes incompatibility problems.
To prevent any future problems, is recommended to use another strategy to read the length of the pulse (in microseconds), like using `micros()`.

**Comment by OtacilioN** [comment]
Working to implement the timeout and complete this issue
